### PR TITLE
Test Xts128::<Aes256>, and compare with openssl directly

### PR DESCRIPTION
**Pull request by jmpesp**
Add tests for Xts128::<Aes256> support, and compare with openssl implementations using the Rust bindings. Remove hard coded test files.

Let me know if you want me to put the hard coded test files back in or if you like this approach. Also, I learned about the cargo-readme crate today, so I ran it to generate the README.md update this time :)

### CODE REVIEW

**Comment by pheki** [comment]
Hey, this looks great! I haven't documented the `README.md` generation anywhere, so it was really hard to guess ;)

I usually try to avoid dynamic dependencies (as the user is forced to install openssl to run tests), but I feel like this is not only able to support test changes much more directly, but also makes the data reference generation self-documented.

There are only a few unresolved details:

- The criterion group is named "xts 256", which makes it look like it's using XTS with 256-bit blocks, not XTS-128 with AES-256. Renaming the group to "xts 128 aes 128" and "xts 128 aes 256" or something like that would be ideal.
- Although using random keys and data in the tests may make it possible to catch edge cases, it makes the tests not reproducible: they may fail only sometimes, independent if the affected code is changed or not. For random tests AFAIK the wisdom to use a fuzzing library such as [afl](https://github.com/rust-fuzz/afl.rs), but that would require more work. By removing random generation from these tests, we would still need to save at least one version of each file (decrypted), but it could be easier to just keep both. Do you have an opinion on this?

**Comment by jmpesp** [comment]
> I usually try to avoid dynamic dependencies (as the user is forced to install openssl to run tests), but I feel like this is not only able to support test changes much more directly, but also makes the data reference generation self-documented.

:+1: I made openssl an optional feature in 8eb15640f76c7e38f89c8491111b901f7aff63c2. Now to install and run them you need to use `cargo test --features "openssl_tests"`.

> The criterion group is named "xts 256", which makes it look like it's using XTS with 256-bit blocks, not XTS-128 with AES-256. Renaming the group to "xts 128 aes 128" and "xts 128 aes 256" or something like that would be ideal.

Done in 7878acd541b7f863b15db913a137f53f7fc854b2.

> Although using random keys and data in the tests may make it possible to catch edge cases, it makes the tests not reproducible: they may fail only sometimes, independent if the affected code is changed or not.

This is a good point - I brought the file-based tests back in 8eb15640f76c7e38f89c8491111b901f7aff63c2.

**Comment by pheki** [comment]
I've merged this and then later also added file tests for AES-256 in 050df6e

Thank you a lot again! 😄

**Comment by jmpesp** [comment]
Thanks :) Curious, how did you generate those test files? The `openssl` command won't use XTS ciphers anymore

**Comment by pheki** [comment]
Hmmmm I was using the MacOS native openssl command, which seems to actually be LibreSSL:

```shell
$ openssl version
LibreSSL 2.8.3
```

You're right though: the native OpenSSL on arch linux (the homebrew openssl on mac), both OpenSSL 1.1.1l, do not seem to support XTS:

```
# Actual openssl
$ openssl version
OpenSSL 1.1.1l  24 Aug 2021
$ openssl enc -aes-256-xts
enc XTS ciphers not supported
```

I was able to use XTS on linux by installing `libressl` via pacman and running `libressl-openssl` instead ;)

**Pull request merged**
